FunInMotion/FunInMotion.Giphy.Web/Controllers/AccountController.cs
using FunInMotion.Gif.Model;
using System.Security.Principal;
using System.Web.Mvc;
using System.Web.Security;

namespace FunInMotion.Gif.Web.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        IUserDomain _userDomain;


        public AccountController(IUserDomain userDomain)
        {
            _userDomain = userDomain;
        }

        // GET: Account
        [AllowAnonymous]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(FunInMotion.Gif.Model.User user)
        {
            if (ModelState.IsValid)
            {
                //Query if the user/account already taken
                if (!_userDomain.IsAccountExist(user.Login))
                {
                    //Add new user account
                    _userDomain.InsertUser(user);
                    FormsAuthentication.SetAuthCookie(user.Login, false);
                    return RedirectToAction("Welcome", "Home");
                }
                else
                {
                    ModelState.AddModelError("AccountExist","Login name is already exist!");
                }

            }

            return View();
        }

        [AllowAnonymous]
        public ActionResult LogIn()
        {
            return View();
        }

        [Authorize]
        public ActionResult SignOut()
        {
            //Response.Cache.SetExpires(DateTime.Now);
            //Response.Cache.SetCacheability(HttpCacheability.NoCache);
            //FormsAuthentication.SignOut();
            //Session.Abandon();
            //Response.Cookies.Clear();

            FormsAuthentication.SignOut();
            HttpContext.User = new GenericPrincipal(new GenericIdentity(string.Empty), null);
            Session.Abandon();
            FormsAuthentication.RedirectToLoginPage();
            HttpContext.ApplicationInstance.CompleteRequest();
            return RedirectToAction("LogIn");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(FunInMotion.Gif.Model.UseViewModel user)
        {
            if (ModelState.IsValid)
            {
                //Check if the user exist
                var isValidUser = _userDomain.AuthenticateUser(user);
                if (!isValidUser)
                {
                    ModelState.AddModelError("LoginError", "Login name or password provided is incorrect.");
                    return View();
                }
                else
                {
                    FormsAuthentication.RedirectFromLoginPage(user.Login, false);
                }
            }
            return View();
        }
    }
}

FunInMotion/FunInMotion.Giphy.Web/Controllers/GalaryController.cs
using FunInMotion.Gif.DomainLogic;
using FunInMotion.Gif.Model;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;
namespace FunInMotion.Gif.Web.Controllers
{
    [Authorize]
    public class GalaryController : Controller
    {
        IUserDomain _userDomain;
        IGiphyService _giphyService;
        IImageDomain _imageDomain;
        ICategoryDomain _categoryDomain;


        public GalaryController(IUserDomain userDomain,
            IGiphyService giphyService,
            IImageDomain imageDomain,
            ICategoryDomain categoryDomain)
        {
            _userDomain = userDomain;
            _giphyService = giphyService;
            _imageDomain = imageDomain;
            _categoryDomain = categoryDomain;
        }

        public ActionResult UpdateImageCategory(int imageId, int categoryid)
        {
            _imageDomain.UpdateImageCategory(imageId, categoryid);
            return this.Json(new
            {
                success = true,
                message = ""
            });
        }

        public ActionResult SetImageFavourite(int imageId, bool isFavourite)
        {
            _imageDomain.UpdateImageFavourite(imageId, isFavourite);
            return this.Json(new
            {
                success = true,
                message = "add"
            });
        }

        public ActionResult Index()
        {
            var categoryLookup = _categoryDomain.GetCateroryList();
            ViewBag.Category = new SelectList(categoryLookup, "CategoryId", "CategoryName"); ;

            var model = _userDomain.GetUserImageGalleries(User.Identity.GetUserName());
            return View(model);
        }

        public ActionResult UserGallery()
        {
            var model = new GalleryByCategoryViewModel();

            return View(model);
        }
    }
    
}

FunInMotion/FunInMotion.Giphy.Web/Controllers/GiphyController.cs
using FunInMotion.Gif.DomainLogic;
using FunInMotion.Gif.Model;
using Microsoft.AspNet.Identity;
using System.Web.Mvc;

namespace FunInMotion.Gif.Web.Controllers
{
    [Authorize]
    public class GiphyController : Controller
    {
        IUserDomain _userDomain;
        IGiphyService _giphyService;
        IImageDomain _imageDomain;


        public GiphyController(IUserDomain userDomain, 
            IGiphyService giphyService,
            IImageDomain imageDomain)
        {
            _userDomain = userDomain;
            _giphyService = giphyService;
            _imageDomain = imageDomain;
        }


        public async System.Threading.Tasks.Task<ActionResult> Index()
        {
            var model = await _giphyService.SearchGif("Dog");
            ViewBag.PageInformation = _giphyService.GetPageInformation(model);
            return View(model);
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Search(string searchterm)
        {
            var model = await _giphyService.SearchGif(searchterm);
            ViewBag.PageInformation = _giphyService.GetPageInformation(model);
            return PartialView("_SearchResult", model);
        }

        [HttpPost]
        public ActionResult AddToFavourites(bool addedtofavourite, string smallimageurl, string largeImageUrl) //This must be replace with a model
        {
            //TEMP ONLY
            var selectedImage = new UserImageModel
            {
                CategoryId = 1,
                IsFavourite = addedtofavourite,
                ThumbnailSizeImageUrl = smallimageurl,
                 LargeSizeImageUrl = largeImageUrl,
                UserId = _userDomain.GetUserByLoginName(User.Identity.GetUserName()).UserId
            };

            _imageDomain.AddImageToGallery(selectedImage);

            return this.Json(new
            {
                success = true,
                message = addedtofavourite ? "add" : ""
            });
        }

     

        [HttpPost]
        public ActionResult AddToGallery(UserImageModel selectedImage)
        {
            selectedImage.IsFavourite = false;
            selectedImage.UserId = _userDomain.GetUserByLoginName(User.Identity.GetUserName()).UserId;
            _imageDomain.AddImageToGallery(selectedImage);
            return this.Json(new
            {
                success = true,
                message = ""
            });
        }

    }
}

FunInMotion/FunInMotion.Giphy.Web/Views/Galary/Index.cshtml
@model IEnumerable<FunInMotion.Gif.Model.UserImageModel>
@{
    ViewBag.Title = "Home Page";
}

<style>

    .heart-color-gray {
        color: gray;
    }

    .heart-color-red {
        color: red;
    }

    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>

@Html.Partial("_NavigationBar")

<br />
<hr />
<div class="row">
    <nav aria-label="...">
        <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
        </ul>
    </nav>
</div>
<div class="row searchresult">
    @{
        Html.RenderPartial("_SearchResultGallery", Model);
    }
</div>
<!-- Modal -->
<div id="modal">
    <div class="row">
        <div class="col-md-6">
            <img  id="imagepreview" src="" alt="No Image" class="center" style="height: 200px; width: 250px;">
        </div>
        <div class="col-md-6">
                 @Html.DropDownList("Category", ViewBag.Category as SelectList, "Select ...", new { htmlAttributes = new { @class = "form-control", @autocomplete = "nope", style = "width: 450px;" } })
                
            <button type="button" class="btn btn-primary btn-xs" 
                    data-toggle="button" id="saveimagecategory"
                    aria-pressed="false" autocomplete="off">Save
            </button>
                
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var selectedImageId;
        $(document).ready(function () {
            $("#modal").iziModal({
                title: 'CATEGORY',
                headerColor: '#88A0B9',
                closeOnEscape: true,
                closeButton: true,
                transitionIn: 'comingIn',
                transitionOut: 'comingOut',
                transitionInOverlay: 'fadeIn',
                transitionOutOverlay: 'fadeOut',
                width: 700,
                radius: 5,
                padding: 20,
            });

            $('.searchresult').delegate('.addtofavourite', "click", function (event) {
                var that = $(this);
                var adddtofav = !$(that).hasClass('addedtofav');
                selectedImageId = $(that).data('id');
                var selectedCategoryId = $('#Category').val();
                $.ajax({
                    url: "Galary/SetImageFavourite",
                    dataType: 'json',
                    type: "POST",
                    data: { "imageId": selectedImageId, "isFavourite": adddtofav },
                    success: function (data) {
                        if (data.success) {
                            if (data.message === "add") {
                                $(that).addClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-gray').addClass('heart-color-red');
                            } else {
                                $(that).removeClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-red').addClass('heart-color-gray');
                            };
                        }
                    },
                    error: function (xhr, status, error) {
                        //error msg here if neccessary
                    }
                });

            });

            $('.searchresult').delegate('.addtomygallery', "click", function (event) {
                var that = $(this);
                var thumbnailUrl = $(that).data('thumbnailurl');
                var largeImageUrl = $(that).data('largesizeurl');
                var sourceid = $(that).data('id');
                var adddtofav = !$(that).hasClass('addedtofav');
                var Image = { ThumbnailSizeImageUrl: thumbnailUrl, LargeSizeImageUrl: largeImageUrl, CategoryId: 1, SourceId: sourceid }
                $.ajax({
                    url: "Giphy/AddToGallery",
                    contentType: 'application/json',
                    type: "POST",
                    data: "{selectedImage:" + JSON.stringify(Image) + "}",
                    success: function (data) {
                        if (data.success) {
                            if (data.message === "add") {
                                $(that).addClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-gray').addClass('heart-color-red');
                            } else {
                                $(that).removeClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-red').addClass('heart-color-gray');
                            };
                        } else {
                            alert('Failed');
                        }
                    }
                });
            });

            $('#gifsearch').click(function (event) {
                var searchterm = $('#search_term_entry').val();

                $.ajax({
                    url: "Giphy/Search",
                    dataType: 'html',
                    type: "POST",
                    data: { "searchterm": searchterm },
                    success: function (data) {
                        $('.searchresult').html(data);
                    },
                    error: function (xhr, status, error) {
                        alert('mali: ' + error);
                    }
                });
            })

            $('.searchresult').delegate('.addcategory', "click", function (event) {
                event.preventDefault();
                var that = $(this);
                var thumbnailUrl = $(that).data('thumbnailurl');
                selectedImageId = $(that).data('id');
                var firstChild = $('#imagepreview');
                firstChild.attr('src', thumbnailUrl);
               
                //$(firstChild).attr('src', thumbnailUrl);
                // $('#modal').iziModal('setZindex', 99999);
                // $('#modal').iziModal('open', { zindex: 99999 });
                $('#modal').iziModal('open');
            });

            $('#saveimagecategory').click(function (e) {
                var selectedCategoryId = $('#Category').val();
                $.ajax({
                    url: "Galary/UpdateImageCategory",
                    dataType: 'json',
                    type: "POST",
                    data: { "imageId": selectedImageId, "categoryid": selectedCategoryId },
                    success: function (data) {
                        if (data.success) {
                            //Dislay toastr
                        }
                    },
                    error: function (xhr, status, error) {
                        //error msg here if neccessary
                    }
                });

            });
        })
    </script>
}

FunInMotion/FunInMotion.Giphy.Web/Views/Giphy/Index.cshtml
@model FunInMotion.Gif.Model.ImagePagination
@{
    ViewBag.Title = "Home Page";
}

<style>
    /*div.imagerow {
        margin-top: 20px;
    }

    html > /**/ body .caption > nav {
        margin-top -15px !important;
        margin-bottom: 2px !important;
    }*/

    .heart-color-gray {
        color: gray;
    }

    .heart-color-red {
        color: red;
    }
    
    /*.thumbnail {
        border: 0 solid transparent;
    }*/
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
@Html.Partial("_NavigationBar")

<br />
<hr />
<div class="row">
    <nav aria-label="...">
        <ul class="pager">
            <li><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
        </ul>
    </nav>
</div>
<div class="row searchresult">
    @{
        Html.RenderPartial("_SearchResult", Model);
    }
</div>

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.searchresult').delegate('.addtofavourite', "click", function (event) {
                var that = $(this);
                var thumbnailUrl = $(that).data('thumbnailurl');
                var largeImageUrl = $(that).data('largesizeurl');
                var sourceid = $(that).data('id');
                var adddtofav = !$(that).hasClass('addedtofav');

                $.ajax({
                    url: "Giphy/AddToFavourites",
                    dataType: 'json',
                    type: "POST",
                    data: { "addedtofavourite": adddtofav, "smallimageurl": thumbnailUrl },
                    success: function (data) {
                        if (data.success) {
                            if (data.message === "add") {
                                $(that).addClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-gray').addClass('heart-color-red');
                            } else {
                                $(that).removeClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-red').addClass('heart-color-gray');
                            };
                        } else {
                            alert('Failed');
                        }
                    }
                });
            });

            $('.searchresult').delegate('.addtomygallery', "click", function (event) {
                var that = $(this);
                var thumbnailUrl = $(that).data('thumbnailurl');
                var largeImageUrl = $(that).data('largesizeurl');
                var sourceid = $(that).data('id');
                var adddtofav = !$(that).hasClass('addedtofav');
                var Image = { ThumbnailSizeImageUrl: thumbnailUrl, LargeSizeImageUrl: largeImageUrl, CategoryId: 1, SourceId: sourceid }
                $.ajax({
                    url: "Giphy/AddToGallery",
                    contentType: 'application/json',
                    type: "POST",
                    data: "{selectedImage:" + JSON.stringify(Image) + "}",
                    success: function (data) {
                        if (data.success) {
                            if (data.message === "add") {
                                $(that).addClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-gray').addClass('heart-color-red');
                            } else {
                                $(that).removeClass("addedtofav");
                                $(that).find('i').removeClass('heart-color-red').addClass('heart-color-gray');
                            };
                        } else {
                            alert('Failed');
                        }
                    }
                });
            });

            $('#gifsearch').click(function (event) {
                var searchterm = $('#search_term_entry').val();

                $.ajax({
                    url: "Giphy/Search",
                    dataType: 'html',
                    type: "POST",
                    data: { "searchterm": searchterm },
                    success: function (data) {
                        $('.searchresult').html(data);
                    },
                    error: function (xhr, status, error) {
                        alert('mali: ' + error);
                    }
                });
            })


        })
    </script>
}

FunInMotion/FunInMotion.Giphy.Web/Views/Shared/NavigationLink.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <ul class="nav navbar-nav">
       <li>
            @Html.ActionLink("My Gallery", "Index", "Galary", null, new { @class = "nav-link" })
       <li>
            @Html.ActionLink("Giphy", "Index", "Giphy", null, new { @class = "nav-link" })
        </li>
    </ul>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" id="search_term_entry" class="form-control" placeholder="Search (Ex: CAT)" >
        </div>
        <a class="btn btn-default" style="cursor: pointer" alt="Thumbnail view" id="gifsearch"> <i class="glyphicon glyphicon-search"></i></a>
        <span class="label label-primary" style="margin-left:15px;">Hello  @User.Identity.GetUserName()</span>
        @Html.ActionLink("Logout", "SignOut", "Account", null, new { @class = "nav-link" })
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li>
            @Html.ActionLink("Register", "SignUp", "Account", null, new { @class = "nav-link" })
        </li>
        <li>
            @Html.ActionLink("Login", "LogIn", "Account", null, new { @class = "nav-link  active" })
        </li>
    </ul>
}

FunInMotion/FunInMotion.Giphy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fun-In-Motion", "Index", "Giphy", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("NavigationLink")
            </div>
        </div>
    </div>*@




    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FunInMotion/FunInMotion.Giphy.Web/Views/Shared/_NavigationBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Fun-In-Motion", "Index", "Giphy", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            @Html.Partial("NavigationLink")
        </div>
    </div>
</div>

FunInMotion/FunInMotion.Giphy.Web/Views/Shared/_SearchResult.cshtml
@using System.Web;
@model FunInMotion.Gif.Model.ImagePagination

@{
    int counter = 0;
}

<div class="row">
    <div class="col-md-4" id="pageinformation">
        @ViewBag.PageInformation
    </div>
</div>
<div class="row imagerow">
    @foreach (var image in Model.ImageCollection)
    {
        if (counter != 0 && counter % 4 == 0)
        {
            @:</div>
            @:<div class="row imagerow">
        }

        <div class="col-sm-6  col-md-3">
            <div class="thumbnail ">
                <a href="@image.LargeSizeImageUrl" data-lightbox="@image.Name" data-title="My caption">
                    <img src="@image.ThumbnailSizeImageUrl" alt="@image.Name" class="center" style="height: 200px; width: 250px;" />
                </a>
            </div>
            <div class="caption">
                <nav aria-label="...">
                    <ul class="pager">
                        <li class="next">
                            <a class="addtomygallery" style="cursor: pointer" data-id="@image.SourceId"
                               data-thumbnailurl="@image.ThumbnailSizeImageUrl"
                               data-largesizeurl="@image.LargeSizeImageUrl">
                       <i class="glyphicon glyphicon-plus"></i>
                            </a>
                            <a class="addtofavourite" style="cursor: pointer" data-id="@image.SourceId"
                               data-thumbnailurl="@image.ThumbnailSizeImageUrl"
                               data-largesizeurl="@image.LargeSizeImageUrl">
                                <i class="glyphicon glyphicon-heart heart-color-gray"></i>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    }
</div>

FunInMotion/FunInMotion.Giphy.Web/Views/Shared/_SearchResultGallery.cshtml
@model IEnumerable<FunInMotion.Gif.Model.UserImageModel>

@{
    int counter = 0;
}

<div class="row">
    <div class="col-md-4" id="pageinformation">
        @*@ViewBag.PageInformation*@
    </div>
</div>
<div class="row imagerow">
    @foreach (var image in Model)
    {
        if (counter != 0 && counter % 4 == 0)
        {
            @:</div>
            @:<div class="row imagerow">
        }

        <div class="col-sm-6  col-md-3">
            <div class="thumbnail ">
                <a href="@image.LargeSizeImageUrl">
                    <img src="@image.ThumbnailSizeImageUrl" alt="@image.Name" class="center" style="height: 200px; width: 250px;" />
                </a>
            </div>
            <div class="caption">
                <nav aria-label="...">
                    <ul class="pager">
                        <li class="previous">
                            <a class="addcategory" style="cursor: pointer" data-id="@image.ImageId"
                               data-thumbnailurl="@image.ThumbnailSizeImageUrl"
                               data-largesizeurl="@image.LargeSizeImageUrl">
                                <i class="glyphicon glyphicon-tags">@image.CategoryName</i>
                            </a>
                        </li>
                        <li class="next">
                            <a class="removetomygallery" style="cursor: pointer" data-id="@image.ImageId"
                               data-thumbnailurl="@image.ThumbnailSizeImageUrl"
                               data-largesizeurl="@image.LargeSizeImageUrl">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                            <a class="addtofavourite" style="cursor: pointer" data-id="@image.ImageId"
                               data-thumbnailurl="@image.ThumbnailSizeImageUrl"
                               data-largesizeurl="@image.LargeSizeImageUrl">
                                <i class="glyphicon glyphicon-heart @(image.IsFavourite ? "heart-color-red" : "heart-color-gray")"></i>
                                
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    }
</div>